# Generated by Django 4.0.5 on 2022-06-28 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_menus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menus',
            name='breakfast',
        ),
        migrations.RemoveField(
            model_name='menus',
            name='lunch',
        ),
        migrations.AddField(
            model_name='menus',
            name='breakfast_1',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='menus',
            name='breakfast_2',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='menus',
            name='breakfast_3',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='menus',
            name='breakfast_4',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='menus',
            name='breakfast_5',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='menus',
            name='breakfast_main',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menus',
            name='dinner_1',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='menus',
            name='dinner_2',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='menus',
            name='dinner_3',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='menus',
            name='dinner_4',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='menus',
            name='dinner_5',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='menus',
            name='lunch_1',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='menus',
            name='lunch_2',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='menus',
            name='lunch_3',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='menus',
            name='lunch_4',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='menus',
            name='lunch_5',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='menus',
            name='lunch_main',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menus',
            name='dinner',
            field=models.CharField(max_length=20),
        ),
    ]
