# Generated by Django 4.0.4 on 2022-06-28 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=200)),
                ('vote_quantity', models.IntegerField()),
                ('vote_users', models.CharField(max_length=200)),
            ],
        ),
    ]
