# Generated by Django 4.0.4 on 2022-06-28 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='vote_users',
            field=models.JSONField(),
        ),
    ]
