# Generated by Django 4.0.5 on 2022-07-02 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_menus_breakfast_remove_menus_lunch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menus',
            name='breakfast_1',
            field=models.CharField(choices=[('-------', '-------'), ('Bolo', 'Bolo'), ('Café/Leite', 'Café/Leite'), ('Mingau', 'Mingau'), ('Pães com Manteiga', 'Pães com Manteiga'), ('Prato Quente', 'Prato Quente')], default='-------', max_length=30),
        ),
        migrations.AlterField(
            model_name='menus',
            name='breakfast_2',
            field=models.CharField(choices=[('-------', '-------'), ('Bolo', 'Bolo'), ('Café/Leite', 'Café/Leite'), ('Mingau', 'Mingau'), ('Pães com Manteiga', 'Pães com Manteiga'), ('Prato Quente', 'Prato Quente')], default='-------', max_length=30),
        ),
        migrations.AlterField(
            model_name='menus',
            name='breakfast_3',
            field=models.CharField(choices=[('-------', '-------'), ('Bolo', 'Bolo'), ('Café/Leite', 'Café/Leite'), ('Mingau', 'Mingau'), ('Pães com Manteiga', 'Pães com Manteiga'), ('Prato Quente', 'Prato Quente')], default='-------', max_length=30),
        ),
        migrations.AlterField(
            model_name='menus',
            name='breakfast_4',
            field=models.CharField(choices=[('-------', '-------'), ('Bolo', 'Bolo'), ('Café/Leite', 'Café/Leite'), ('Mingau', 'Mingau'), ('Pães com Manteiga', 'Pães com Manteiga'), ('Prato Quente', 'Prato Quente')], default='-------', max_length=30),
        ),
        migrations.AlterField(
            model_name='menus',
            name='breakfast_5',
            field=models.CharField(choices=[('-------', '-------'), ('Bolo', 'Bolo'), ('Café/Leite', 'Café/Leite'), ('Mingau', 'Mingau'), ('Pães com Manteiga', 'Pães com Manteiga'), ('Prato Quente', 'Prato Quente')], default='-------', max_length=30),
        ),
        migrations.AlterField(
            model_name='menus',
            name='breakfast_main',
            field=models.CharField(choices=[('-------', '-------'), ('Bolo', 'Bolo'), ('Café/Leite', 'Café/Leite'), ('Mingau', 'Mingau'), ('Pães com Manteiga', 'Pães com Manteiga'), ('Prato Quente', 'Prato Quente')], max_length=30),
        ),
        migrations.AlterField(
            model_name='menus',
            name='dinner',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='menus',
            name='dinner_1',
            field=models.CharField(choices=[('-------', '-------'), ('Almondegas ao Sugo', 'Almondegas ao Sugo'), ('Carne Assado', 'Carne Assada'), ('Carne em Cubos ao Molho Shoyu', 'Carne em Cubos ao Molho Shoyu'), ('Carne Moída com Milho', 'Carne Moída com Milho'), ('Estrogonofe de Carne', 'Estrogonofe de Carne'), ('Filé de Frango Acebolado', 'Filé de Frango Acebolado'), ('Filezinho à Parmegiana', 'Filezinho à Parmegiana'), ('Linguiça Acebolada', 'Linguiça Acebolada'), ('Lombo Assado/Molho', 'Lombo Assado/Molho'), ('Moqueca de Peixe', 'Moqueca de Peixe'), ('Peixe Frito', 'Peixe Frito'), ('Sobrecoxa Assada', 'Sobrecoxa assada'), ('Steak de Frango à Pizzaiolo', 'Steak de Frango à Pizzaiolo'), ('Torta de Frango', 'Torta de Frango')], default='-------', max_length=30),
        ),
        migrations.AlterField(
            model_name='menus',
            name='dinner_2',
            field=models.CharField(choices=[('-------', '-------'), ('Salada e Arroz/Feijão', 'Salada e Arroz/Feijão'), ('Sobremesa', 'Sobremesa'), ('Refresco', 'Refresco'), ('Batara Palha', 'Batata Palha'), ('Creme de Espinafre', 'Creme de Espinafre'), ('Creme de Milho', 'Creme de Milho'), ('Farofa Rica', 'Farofa Rica'), ('Macarrão ao Molho Branco', 'Macarrão ao Molho Branco'), ('Pirão', 'Pirão')], default='-------', max_length=30),
        ),
        migrations.AlterField(
            model_name='menus',
            name='dinner_3',
            field=models.CharField(choices=[('-------', '-------'), ('Salada e Arroz/Feijão', 'Salada e Arroz/Feijão'), ('Sobremesa', 'Sobremesa'), ('Refresco', 'Refresco'), ('Batara Palha', 'Batata Palha'), ('Creme de Espinafre', 'Creme de Espinafre'), ('Creme de Milho', 'Creme de Milho'), ('Farofa Rica', 'Farofa Rica'), ('Macarrão ao Molho Branco', 'Macarrão ao Molho Branco'), ('Pirão', 'Pirão')], default='-------', max_length=30),
        ),
        migrations.AlterField(
            model_name='menus',
            name='dinner_4',
            field=models.CharField(choices=[('-------', '-------'), ('Salada e Arroz/Feijão', 'Salada e Arroz/Feijão'), ('Sobremesa', 'Sobremesa'), ('Refresco', 'Refresco'), ('Batara Palha', 'Batata Palha'), ('Creme de Espinafre', 'Creme de Espinafre'), ('Creme de Milho', 'Creme de Milho'), ('Farofa Rica', 'Farofa Rica'), ('Macarrão ao Molho Branco', 'Macarrão ao Molho Branco'), ('Pirão', 'Pirão')], default='-------', max_length=30),
        ),
        migrations.AlterField(
            model_name='menus',
            name='dinner_5',
            field=models.CharField(choices=[('-------', '-------'), ('Salada e Arroz/Feijão', 'Salada e Arroz/Feijão'), ('Sobremesa', 'Sobremesa'), ('Refresco', 'Refresco'), ('Batara Palha', 'Batata Palha'), ('Creme de Espinafre', 'Creme de Espinafre'), ('Creme de Milho', 'Creme de Milho'), ('Farofa Rica', 'Farofa Rica'), ('Macarrão ao Molho Branco', 'Macarrão ao Molho Branco'), ('Pirão', 'Pirão')], default='-------', max_length=30),
        ),
        migrations.AlterField(
            model_name='menus',
            name='lunch_1',
            field=models.CharField(choices=[('-------', '-------'), ('Almondegas ao Sugo', 'Almondegas ao Sugo'), ('Carne Assado', 'Carne Assada'), ('Carne em Cubos ao Molho Shoyu', 'Carne em Cubos ao Molho Shoyu'), ('Carne Moída com Milho', 'Carne Moída com Milho'), ('Estrogonofe de Carne', 'Estrogonofe de Carne'), ('Filé de Frango Acebolado', 'Filé de Frango Acebolado'), ('Filezinho à Parmegiana', 'Filezinho à Parmegiana'), ('Linguiça Acebolada', 'Linguiça Acebolada'), ('Lombo Assado/Molho', 'Lombo Assado/Molho'), ('Moqueca de Peixe', 'Moqueca de Peixe'), ('Peixe Frito', 'Peixe Frito'), ('Sobrecoxa Assada', 'Sobrecoxa assada'), ('Steak de Frango à Pizzaiolo', 'Steak de Frango à Pizzaiolo'), ('Torta de Frango', 'Torta de Frango')], default='-------', max_length=30),
        ),
        migrations.AlterField(
            model_name='menus',
            name='lunch_2',
            field=models.CharField(choices=[('-------', '-------'), ('Salada e Arroz/Feijão', 'Salada e Arroz/Feijão'), ('Sobremesa', 'Sobremesa'), ('Refresco', 'Refresco'), ('Batara Palha', 'Batata Palha'), ('Creme de Espinafre', 'Creme de Espinafre'), ('Creme de Milho', 'Creme de Milho'), ('Farofa Rica', 'Farofa Rica'), ('Macarrão ao Molho Branco', 'Macarrão ao Molho Branco'), ('Pirão', 'Pirão')], default='-------', max_length=30),
        ),
        migrations.AlterField(
            model_name='menus',
            name='lunch_3',
            field=models.CharField(choices=[('-------', '-------'), ('Salada e Arroz/Feijão', 'Salada e Arroz/Feijão'), ('Sobremesa', 'Sobremesa'), ('Refresco', 'Refresco'), ('Batara Palha', 'Batata Palha'), ('Creme de Espinafre', 'Creme de Espinafre'), ('Creme de Milho', 'Creme de Milho'), ('Farofa Rica', 'Farofa Rica'), ('Macarrão ao Molho Branco', 'Macarrão ao Molho Branco'), ('Pirão', 'Pirão')], default='-------', max_length=30),
        ),
        migrations.AlterField(
            model_name='menus',
            name='lunch_4',
            field=models.CharField(choices=[('-------', '-------'), ('Salada e Arroz/Feijão', 'Salada e Arroz/Feijão'), ('Sobremesa', 'Sobremesa'), ('Refresco', 'Refresco'), ('Batara Palha', 'Batata Palha'), ('Creme de Espinafre', 'Creme de Espinafre'), ('Creme de Milho', 'Creme de Milho'), ('Farofa Rica', 'Farofa Rica'), ('Macarrão ao Molho Branco', 'Macarrão ao Molho Branco'), ('Pirão', 'Pirão')], default='-------', max_length=30),
        ),
        migrations.AlterField(
            model_name='menus',
            name='lunch_5',
            field=models.CharField(choices=[('-------', '-------'), ('Salada e Arroz/Feijão', 'Salada e Arroz/Feijão'), ('Sobremesa', 'Sobremesa'), ('Refresco', 'Refresco'), ('Batara Palha', 'Batata Palha'), ('Creme de Espinafre', 'Creme de Espinafre'), ('Creme de Milho', 'Creme de Milho'), ('Farofa Rica', 'Farofa Rica'), ('Macarrão ao Molho Branco', 'Macarrão ao Molho Branco'), ('Pirão', 'Pirão')], default='-------', max_length=30),
        ),
        migrations.AlterField(
            model_name='menus',
            name='lunch_main',
            field=models.CharField(max_length=30),
        ),
    ]
