# Generated by Django 4.0.5 on 2022-07-02 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_menus_breakfast_main_alter_menus_dinner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menus',
            name='dinner',
        ),
        migrations.RemoveField(
            model_name='menus',
            name='url',
        ),
        migrations.AddField(
            model_name='menus',
            name='dinner_main',
            field=models.CharField(choices=[('-------', '-------'), ('Almondegas ao Sugo', 'Almondegas ao Sugo'), ('Carne Assada', 'Carne Assada'), ('Carne em Cubos ao Molho Shoyu', 'Carne em Cubos ao Molho Shoyu'), ('Carne Moída com Milho', 'Carne Moída com Milho'), ('Estrogonofe de Carne', 'Estrogonofe de Carne'), ('Filé de Frango Acebolado', 'Filé de Frango Acebolado'), ('Filezinho à Parmegiana', 'Filezinho à Parmegiana'), ('Linguiça Acebolada', 'Linguiça Acebolada'), ('Lombo Assado/Molho', 'Lombo Assado/Molho'), ('Moqueca de Peixe', 'Moqueca de Peixe'), ('Peixe Frito', 'Peixe Frito'), ('Sobrecoxa Assada', 'Sobrecoxa assada'), ('Steak de Frango à Pizzaiolo', 'Steak de Frango à Pizzaiolo'), ('Torta de Frango', 'Torta de Frango')], default='-------', max_length=30),
        ),
        migrations.AlterField(
            model_name='menus',
            name='lunch_main',
            field=models.CharField(choices=[('-------', '-------'), ('Almondegas ao Sugo', 'Almondegas ao Sugo'), ('Carne Assada', 'Carne Assada'), ('Carne em Cubos ao Molho Shoyu', 'Carne em Cubos ao Molho Shoyu'), ('Carne Moída com Milho', 'Carne Moída com Milho'), ('Estrogonofe de Carne', 'Estrogonofe de Carne'), ('Filé de Frango Acebolado', 'Filé de Frango Acebolado'), ('Filezinho à Parmegiana', 'Filezinho à Parmegiana'), ('Linguiça Acebolada', 'Linguiça Acebolada'), ('Lombo Assado/Molho', 'Lombo Assado/Molho'), ('Moqueca de Peixe', 'Moqueca de Peixe'), ('Peixe Frito', 'Peixe Frito'), ('Sobrecoxa Assada', 'Sobrecoxa assada'), ('Steak de Frango à Pizzaiolo', 'Steak de Frango à Pizzaiolo'), ('Torta de Frango', 'Torta de Frango')], default='-------', max_length=30),
        ),
    ]
